version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: remote-index-build-service
    container_name: remote-index-build-service
    ports:
      - "5005:5005"
    environment:
    # Set environment variables
    # remove these variables for production
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./logs:/app/logs
    user: appuser
    command: python app.py

volumes:
  logs:
