services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: remote-index-build-service-worker
    container_name: remote-index-build-service-worker
    networks:
      - remote-index-build-service-network
    ports:
      - "6005:6005"
    environment:
    # Set environment variables
    # remove these variables for production
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - INDEX_BUILD_TYPE=${INDEX_BUILD_TYPE} # valid values cpu, gpu
    volumes:
      - ./logs:/app/logs
    user: appuser
    command: python app.py

volumes:
  logs:
